[project]
name = "Spoticord"
version = "0.1.0"
description = "Spotify discord playlist bot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["PyYAML", "discord", "spotipy", "requests"]
